name: 'CheckActionsBillingInfo'
description: 'check actions billing info'
author: 'starfish719'
inputs:
  accessToken:
    required: true
    description: 'GitHub Access Token'
    default: ''
  username:
    required: true
    description: 'User Name'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'blue'